### PR TITLE
Upgrade preact

### PR DESCRIPTION
**Pull request by phocks**
This should technically fix the bugs that occur now that Preact has upgraded to Preact X.

### CODE REVIEW

**Comment by phocks** [comment]
I'm still a bit confused by what this does though `'create-react-class': 'preact-compat/lib/create-react-class'` in the resolve....... and if we need to keep preact-compat in the dependencies because this is not in preact/compat core now. If anyone who knows Preact better wants to have a look (@drzax) then all help will be welcomed. This seems to work though for now.

**Comment by drzax** [comment]
Unfortunately I can't claim to know preact any better, sorry.

**Comment by drzax** [comment]
I upgraded Preact to X in https://github.com/abcnews/quiz-viewer/commit/64f4097e49eca7dae550ed76faf5007e98f1442c

There were no API changes relevant there and `preact-compat` can just be ditch from dependencies. I think this is safe to merge, but I'm also not sure if we need to keep those aliases in the webpack config.

**Comment by colingourlay** [comment]
This will be covered by #115 when it lands, and we'll be able to close this without merging

**Comment by colingourlay** [comment]
This has all been added (thanks for the copy-pastable, @phocks) during the TypeScript feature addition

**Comment by phocks** [comment]
Awesome, cheers @colingourlay

**Pull request closed without merging**
