### PR TITLE
Multiple entry point support

### LINKED ISSUE #131: Support multiple entry points via build config
We've started using multiple entry points to create mulitple build outputs in our projects, but they have to be defined by hacking into the webpack config in `aunty.config.js` like this:

```js
const ADDITIONAL_ENTRY_POINTS = ['editor', 'graphic', 'polyfills'];

module.exports = {
  webpack: config => {
    ADDITIONAL_ENTRY_POINTS.forEach(name => {
      config.entry[name] = [config.entry.index[0].replace('index', name)];
    });

    return config;
  }
};
```

Sometimes we also want to rename the default 'index' entry point:

```js
const MAIN_ENTRY_POINT = 'story';
const ADDITIONAL_ENTRY_POINTS = ['editor', 'graphic', 'polyfills'];

module.exports = {
  build: {
    entry: MAIN_ENTRY_POINT
  },
  webpack: config => {
    [MAIN_ENTRY_POINT].concat(ADDITIONAL_ENTRY_POINTS)
    .forEach(name => {
      config.entry[name] = [config.entry.index[0].replace(MAIN_ENTRY_POINT, name)];
    });
    delete config.entry.index;

    return config;
  }
};
```

I propose we let aunty do all of this under the hood by repurposing the `build::entry` config prop to also support a list of strings to define multiple entry points. Here are some examples of how we'd do this:

#### Replace 'index' with 'story'

```js
module.exports = {
  build: {
    entry: 'story' // will now also support `['story']`
  }
};
```

#### Replace 'index' with 'story', 'editor', 'graphic' & 'polyfills'

```js
module.exports = {
  build: {
    entry: ['story', 'editor', 'graphic', 'polyfills']
  }
};
```

#### Retain 'index'; add 'editor', 'graphic' & 'polyfills'

```js
module.exports = {
  build: {
    entry: ['index', 'editor', 'graphic', 'polyfills']
  }
};
```

This change also fixes a long-standing quirk where the output file was always named `index.js`, no matter what the entry filename was.

What are your thoughts?

### PR DESCRIPTION
**Pull request by colingourlay**
This extends the `build::entry` config prop (previously used to change the expected entry filename from the default `index`) to also accept an array of strings. Each will be considered an entry point.

Now, renaming the default entry point (by setting `build::entry` to a different string, or a unit array, will ensure the output filename matches that entry filename, rather than it being renamed to `index.js`.

If you want to keep the default `index` around, just include it as one of your array items.

Closes #131 (see for reference implementation, and the existing hacks we plan to avoid).

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Excellent. Just what I needed.

**Comment by drzax** [comment]
Looks good. Just suggest adding a usage example somewhere?

**Comment by colingourlay** [comment]
> usage example

Documentation for each command's config object(s) has been sorely missed since we adopted aunty. I definitely need to take the time to do it, rather than us continue the guesswork and queries amongst each other that we've repeated over the years.

I think I'll add it once these all of these changes (and cleanup) have landed. Do you think it should exist in README-style files in this repo, or should we add it to the command help output?

**Comment by drzax** [comment]
I'd probably go with readme-style just because it offers the ability to be more verbose in a more readable format.

**Pull request merged**
