### PR TITLE
Aunty will now build two versions of interactives

### PR DESCRIPTION
**Pull request by nathanhoad**
Aunty now uses `babel-preset-env` to transpile when building. This means we now get two builds - one targeting ES5 compatibility (the default build) and one targeting modern browsers that support things like let, const, arrow functions, etc. 

The benefit of removing excess transpiling is not only that the bundle size is smaller (admittedly not that much for the kinds of things we do) but mostly that parse time is quicker.

Being able to use this in production is still waiting on a PR merge on the actual `init-interactive` loader but everything will work as normal until then (and even after then; usage of the new stuff is optional). When it's ready you can just add `data-modules="<WHATEVER URL>/index.modules.js"` to your usual `init-interactive` div. IE will load the standard file and Chrome, Safari, Firefox, etc will load the modern file.

### CODE REVIEW

**Comment by nathanhoad** [comment]
A super basic example can be seen at:  
http://www.abc.net.au/res/sites/news-projects/interactive-test/1.0.0/

**Comment by colingourlay** [comment]
As this changes the output from one target to two (and some projects using aunty are tweaking target configuration), I'd recommend that this causes a major bump.

**Comment by colingourlay** [comment]
P.S. This closes #33

**Comment by drzax** [comment]
Agree this is a major bump. Also, here's [the initInteractive pr](https://stash.abc-dev.net.au/projects/NEWS/repos/news-www/pull-requests/589/overview) in case you want a look.

**Pull request merged**
