### PR TITLE
New project templates

### PR DESCRIPTION
**Pull request by colingourlay**
This has tried to best capture our the changes we make to every new project these days, in order to accommodate:

- `#`-defined mount points, rather than HTML Fragment-provided `data-*`-attributed `<div>`s
- Alternating-case app props on the mount point
- Waiting on Presentation Layer React DOM hydration (and decoys), or for Odyssey to have done its work

The project generator now asks you if you plan to use this app in an Odyssey, changing the initialisation promise and dispatching a mock `odyssey:api` custom event (in the example `index.html`). It will now install `@abcnews/alternating-case-to-props`, `@abcnews/env-utils` & `@abcnews/mount-utils` dependencies. The `App` component now has different example props in order to show `alternating-case-to-props` at work.

I've pushed [a repo which contains every generated project variant](https://github.com/abcnews/aunty-projects-2021), as the results are easier to examine than the templates (which are littered with alternative sections for TypeScript and Odyssey variants).

_This also brings a couple of bugfixes around styles building for Svelte and Vue, as well as a couple of code-style changes for their components._

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Cool

**Comment by drzax** [comment]
This looks great, thanks @colingourlay!

Does this address #123? 

I also wonder if it's worth considering dropping Vue support to lighten the upkeep load next time big changes are made — probably one for another ticket, but just wanted to float the idea.

I'm happy for this to be merged and released if you're happy with it.

**Review by drzax — APPROVED** [review]

**Comment by colingourlay** [comment]
@drzax #123 is a separate issue, which we'll want to address as part of the generators cleanup. I'm also happy to remove `vue` if it's not getting any love.

**Review by Milliners-Son — APPROVED** [review]
This is great. Moving over to new mount point system will be super helpful.

**Review by andrewkesper — APPROVED** [review]
This is terrific @colingourlay - looks all good to me

**Pull request merged**
